facebook:
  client:
    clientId: 1750768951893553
    clientSecret: f2a49ed418329d655bcec3124bfb9e19
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: public_profile email
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=email,name
google:
  client:
    clientId: 765076073463-daeruipbjvb8b4mmaihmml9ohhjiv2pe.apps.googleusercontent.com
    clientSecret: YVIVU4jstqVvsbV22r5734eo
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri:  https://www.googleapis.com/oauth2/v3/userinfo

    
server:
  port: 8080
  

         